name: Stroking back to life
favicon: null
layout_spectrum: 0.14281461690552533
typography_spectrum: 0.8965579895302653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7530302966479212
  lightness: 0.21960979094728827
  saturation: 0.6761653451249003
  rhythmicContrast: 0.2742463988251984
purpose: []
